### PR TITLE
Fix EZP-23928: Preview cache not being updated

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-23928

Same as https://github.com/ezsystems/ezpublish-legacy/pull/1143

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by lolautruche** [comment]
I think we now need a new release. What do you think @andrerom @bdunogier ?

**Comment by bdunogier** [comment]
Are there many fixes other than this one @lolautruche ?

**Pull request merged**
